### ISSUE TITLE
Migrate to Webpack

### ISSUE THREAD

**Issue by Dwaynekj** [fin-hypergrid/core#525]

**Comment by jjrv** [comment]
I'm using SystemJS to bundle Hypergrid with my app. It's great! It works as-is, I just have to generate a config using: `cbuild -o dist/bundle.js -C config-npm.js` (command from the [`cbuild`](https://github.com/charto/cbuild) package).

Since it's using the Node.js entry point, I have to add this in my own code:

```TypeScript
window.fin = {
    Hypergrid: {analytics: analytics}
};
```

**Comment by Dwaynekj** [comment]
@jjrv Thanks for the suggestion we will keep it under consideration when we get to this project later this spring

**Comment by aqumus** [comment]
I have used fin-hypergrid npm package with basic webpack configuration and it was loading and working fine for me.

**Comment by dcchuck** [comment]
@aqumus TY, confirmed. Closing.
