### ISSUE TITLE
Min File Fails on Dynamic Props

### ISSUE THREAD

**Issue by Dwaynekj** [fin-hypergrid/core#649]
@joneit 
 
I could use some help here

The min file does not correctly resolve `grid.properties.subgrids` nor `grid.properties.gridRenderer` 

I wonder if `this.var` has anything to do with this
https://github.com/fin-hypergrid/core/blob/master/src/lib/dynamicProperties.js#L41 

Also the sourcemap is missing.

**Comment by Dwaynekj** [comment]
@joneit Can you give me a hand here. I lost my debugging environment with the sourcemaps missing.

**Comment by joneit** [comment]
Will address this week. You may be onto something re: `var`.

**Comment by joneit** [comment]
to: @Dwaynekj  cc: @nmichaud 

I found no issues with the min file. I tried a series of complicated dynamic property actions.

The current `develop` branch min file with the current chrome, safari, firefox, and opera. I still need to try it with IE 11.

Perhaps your issue was specific to a past commit in develop's history, or a past version of chrome? (I don't have a past version of chrome on my machine right now. Do you?)

We are still using `uglify-js@2.6.4` and this has not changed from master branch. I will look at upgrading to latest `uglify-js@3.0.0` for `fin-hypergrid@3.0.0` but for now, as I said, nothing has changed.

Jonathan

**Comment by joneit** [comment]
Tested on IE 11. No issues.

**Comment by joneit** [comment]
Tested 2.1.0 release candidate on Chrome 50 (windows 8). No issues.
I'm closing this issue.
