### ISSUE TITLE
Cell contents munged during column resize

### ISSUE THREAD

**Issue by igorii** [fin-hypergrid/core#717]
Tested on master and 2.1.4. See attached gif - the gif moves a bit fast, but watch the last row for clearest example. When resizing a cell to be too small, the cell contents are not properly truncated, and the characters become munged.

![out](https://user-images.githubusercontent.com/2524964/39327601-7cb935dc-4966-11e8-90cd-4dc81a071f0b.gif)

```html
<head>
    <script src="main.js"></script>
</head>
<body>
    <div id="target" style="width:500px;height:864px"></div>
</body>
```
```js
var grid = require('./hypergrid');
document.addEventListener('DOMContentLoaded', function () {
    var g = new grid('#target'), data = [], i;
    for (i = 0; i < 1000); ++i) data.push({ index: i, data: i });
    g.setData(data);
});
```

**Comment by joneit** [comment]
hello @igorii, String truncation and column clipping strategies are controlled by the following two options (respectively):
* [`grid.properties.truncateTextWithEllipsis`](https://fin-hypergrid.github.io/core/doc/module-defaults.html#.truncateTextWithEllipsis)
* [`grid.properties.columnClip`](https://fin-hypergrid.github.io/core/doc/module-defaults.html#.columnClip) 

Currently the default strategy is both to truncate strings _and_ clip columns:

```js
grid.properties.truncateTextWithEllipsis = true;
grid.properties.columnClip = true;
```

This is overkill in most cases and for better performance, we recommend turning clipping off entirely because it is an expensive operation. In fact, we are likely going to change the default `columnClip` setting to `false` in Hypergrid 3.0.0.

In your case, if you don't like the ellipsis, just turn it off:
```js
grid.properties.truncateTextWithEllipsis = false;
grid.properties.columnClip = true;
```

There are other settings (besides `true` and `flase`); follow the links to the API documentation for more details.
