### ISSUE TITLE
how to make dependency injection work with column calculator

### ISSUE THREAD

**Issue by slimtom95** [fin-hypergrid/core#785]
Function factory that using dependency injection not work in current implementation of column calculator. The registered calculator in the following lines will lost its context, cannot resolve `cols` in this case.

```
function sumCalulatorFactory(cols) {
        return function (dataRow, columnName) {
            var result = 0;
            cols.forEach(each => {result += dataRow[each]});
            return result
        }
    };

grid.setColumnProperties(idx, {
                        calculator: sumCalulatorFactory([cols])
                    });
```

If we can support these kind of factories, the column calculator with similar calculation structure can be merged, and they will be able to receive config, which would bring a lot advantages(In my case dozens of calculators could be eliminated).

I haven't looked quite deep into the calculator implementation yet, not sure is there any workaround, glad to hear any advice.

**Comment by joneit** [comment]
You are correct:

> **Calculator functions lose their execution contexts when they are set.**

The reason for this is that the calculator functions are meant to be serializable to facilitate persisting state. They are re-inflated when state is loaded. We don't allow calculators to have their own context because the context cannot be serialized.

### Background

The `properties.calculator` setter has several overloads: registered function name, stringified function object, or actual function object. This last overload is what you are using here. The problem is, as I've said, that we strip the context before storing in the calculators registry.

### Work-around

> **CAVEAT**: The following work-around will create a calculator that depend on its execution context. Saving state will not persist the context of such calculator functions. On reloading the state, the context will have been lost.

"Manually" add your calculator function (with its context intact) to the `calculators` registry and reference that calculator _by name_ in a `calculator` property:
```js
function sumCalculatorFactory(cols) {
    return function (dataRow, columnName) {
        var result = 0;
        cols.forEach(each => {result += dataRow[each]});
        return result;
    }
};

var caculatorsRegistry = myGrid.properties.calculators = myGrid.properties.calculators || {};
caculatorsRegistry.myCalc = sumCalculatorFactory([cols]);

myGrid.setColumnProperties(idx, { calculator: 'myCalc' });
```
### Tip
Other ways to set the column's `calculator` property:
```js
var myColumn = myGrid.behavior.getColumn(idx);
myColumn.properties.calculator = fn;
myColumn.calculator = fn;
```
These are all equivalent.

**Comment by slimtom95** [comment]
Thanks! It works exactly as expected!
